name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4']
        prefer-lowest: ['']
        include:
          - php-version: '8.4'
            prefer-lowest: 'prefer-lowest'

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
       if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
         composer update --no-progress --prefer-lowest --prefer-stable
       else
         composer update --no-progress
       fi

    - name: Run test suite
      run: |
        if [[ ${{ matrix.php-version }} == '8.4' ]]; then
            export XDEBUG_MODE=coverage; vendor/bin/phpunit --coverage-clover=coverage.xml
        else
            composer run-script test
        fi

    - name: Submit code coverage
      if: matrix.php-version == '8.4'
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.4'
            coverage: none
            tools: cs2pr

        - name: Install dependencies
          run: composer install --no-progress

        - name: Run PHP CodeSniffer
          continue-on-error: true
          run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

        - name: Show PHPCS results in PR
          run: cs2pr ./phpcs-report.xml

        - name: Run phpstan
          run: vendor/bin/phpstan analyse --error-format=github

  testsuite-windows:
    runs-on: windows-2019
    name: Windows - PHP 8.4

    env:
      EXTENSIONS: mbstring, intl
      PHP_VERSION: '8.4'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        ini-values: apc.enable_cli = 1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-progress

    - name: Run test suite
      run: composer run-script test
