name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.4']
        dependencies: ['highest']
        include:
          - php-version: '8.4'
            dependencies: 'lowest'

    steps:
      - name: Setup MySQL 8.0
        run: |
          sudo service mysql start
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE test;'

      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: zend.assertions=1
          coverage: pcov

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: Run test suite
        run: |
          export db_dsn_mysqli='mysql://root:root@127.0.0.1/test?encoding=utf8'
          export db_dsn_postgres='postgres://postgres:postgres@127.0.0.1/test'
  
          if [[ ${{ matrix.dependencies }} == 'highest' ]]; then
              export XDEBUG_MODE=coverage; vendor/bin/phpunit --display-skipped --display-phpunit-deprecations --display-deprecations --display-warnings --coverage-clover=coverage.xml
          else
              vendor/bin/phpunit --display-skipped --display-phpunit-deprecations --display-deprecations --display-warnings
          fi

      - name: Code Coverage Report
        if: success() && matrix.dependencies == 'highest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.4'
            coverage: none
            tools: cs2pr

        - name: Install dependencies
          run: composer install --no-progress

        - name: Run PHP CodeSniffer
          continue-on-error: true
          run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

        - name: Show PHPCS results in PR
          run: cs2pr ./phpcs-report.xml

        - name: Run phpstan
          run: vendor/bin/phpstan analyse --error-format=github

  testsuite-windows:
    runs-on: windows-2019
    name: Windows - PHP 8.4

    env:
      EXTENSIONS: mbstring, intl
      PHP_VERSION: '8.4'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        ini-values: apc.enable_cli = 1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-progress

    - name: Run test suite
      run: composer run-script test
